### PR TITLE
allow use of tsv format for samples

### PR DESCRIPTION
**Pull request by ninjha01**
Should solve #27

### CODE REVIEW

**Comment by nsheff** [comment]
This relies on file extension to be accurate. Isn't the solution proposed in #27 superior as it will automatically get it right, regardless of file extension?

**Comment by ninjha01** [comment]
Read_table caused errors in testing that I couldn't easily debug, and upon looking at 
[the documentation...](http://pandas.pydata.org/pandas-docs/stable/io.html)
> sep : str, defaults to ',' for read_csv(), \t for read_table()
>     Delimiter to use. If sep is None, the C engine cannot automatically detect the separator, but the Python parsing engine can, meaning the latter will be used automatically. 

...it seemed like there wasn't a huge difference between the two functions.

**Comment by vreuter** [comment]
I'm OK with either way, but `read_table` with explicit `sep=None` may be a tad cleaner/more succinct. 
If we do go with extension, I think that the check should be csv-first and account for case, then fallback to tab. Something like:
```
if extension.lower() == ".csv":
    <read-csv-call>
else:
    <tab-based fallback call>
```

**Comment by vreuter** [comment]
`read_table` errors could be related to default row indexing behavior...`index_col=False` may do the trick if so.

**Comment by nsheff** [comment]
I think it's worth trying to figure out how to do it automatically so we don't have to reinvent the wheel here.

Also if relying on extension (which I think is a bad idea)  should we throw an error if an incorrect extension is given, then?

**Comment by vreuter** [comment]
Agree, I think `read_table` with `sep=None` is best. With extension route, I don't have a strong preference between raising our own exception vs. letting `read_table` do its own thing. If extension-checking, I think the first case is CSV, second is [TSV/TXT] (all case-agnostic), then exception.

**Comment by ninjha01** [comment]
I'm having trouble getting `read_table` to guess file types.

`pd.read_table(sample_file, sep=",", engine='python', index_col=False)` 

works without a hitch on csv's, but 

`pd.read_table(sample_file, sep=None, engine='python', index_col=False)`

fails with the following error:

`ValueError: Annotation sheet ('/tmp/pytest-of-nj7kv/pytest-25/test_minimal_configuration_out0/anns.csv') is missing column(s): sample_name`

@nsheff @vreuter any ideas?

**Comment by vreuter** [comment]
Can you push whatever changes you have so that I can run the tests and see the full traceback?

**Comment by nsheff** [comment]
I don't nkow how pandas read_table works. if this doesnt work we could aslo try `csv.Sniffer` [see here](https://stackoverflow.com/questions/16312104/can-i-import-a-csv-file-and-automatically-infer-the-delimiter).

**Comment by vreuter** [comment]
The tests :heart: the changes now; I'm good to merge this; what do you think @nsheff ?

**Comment by nsheff** [comment]
I'm getting errors:
` The 'dtype' option is not supported with the 'python' engine`

**Comment by vreuter** [comment]
OK I can check it out

**Pull request merged**
