### PR TITLE
More general models

### PR DESCRIPTION
**Pull request by vreuter**
Addresses/tests the first few 3 items in https://github.com/epigen/looper/issues/93.
I think that any checks for `library` are confined to the looper portion of the code. `data_source` is no longer appended to the `models` `Project` as a derived column, and the attempt to achieve other separation is implemented by subclassing the `models` `Project` with a few overrides for the `looper` specific version. Some exceptions have been replaced with builtins so that `models` isn't importing from `looper.exceptions`.

### CODE REVIEW

**Comment by vreuter** [comment]
@nsheff perhaps you can run a few of your projects as test cases, as I've probably broken something that's not covered by the automated tests. @afrendeiro I tinkered a bit with the way in which `Sample` subclasses are handled, but not a ton so hopefully that's still in working order. If you have time to check that out let me know if you have some thoughts on it.

**Comment by vreuter** [comment]
Now closes #93 I think, with the fourth item (`run` --> `toggle`) now included.

**Comment by nsheff** [comment]
Can you describe in more detail "subclassing the models Project with a few overrides for the looper specific version." -- what exactly do we need to do in `looper` that doesn't fit in the generic `Project` that necessitates a subclass?

**Comment by vreuter** [comment]
Yeah sure, maybe I should write a little of this in the docs and/or docstrings, too, for clarity and so we remember down the road. I think mostly overrides it's motivated by the separation broadly, and somewhat more specifically by the tasks in https://github.com/epigen/looper/issues/93. For instance `required_metadata` and `project_folders` are redefined for the `looper`-specific presumption of `output_dir`, the constructor specifies default environment settings that we have in `looper`, and the name inference and sample sheet addition methods tweak the base `models` versions to match the way we typically structure `looper` projects and use `derived_columns` / "data_source," respectively, that I think should not be relied upon in the more general `models` version.

**Comment by nsheff** [comment]
Ok, makes sense -- I think `derived_columns` should be pretty universal, though, no?

**Comment by vreuter** [comment]
Agree. Let me see if I can work this back into general modes.

**Comment by vreuter** [comment]
OK, derived_columns has moved back to general `models`.

**Comment by nsheff** [comment]
Ok thanks. A few other comments:
 * can you make a round of docs updates? in particular the run -> toggle thing should be in docs.
* why did you remove `data_source` ? 
> data_source is no longer appended to the models Project as a derived column

**Comment by vreuter** [comment]
Yeah definitely, will do. Is it still removed as of most recent commit? I had taken it out but it should've returned now.

**Comment by nsheff** [comment]
I didn't notice, sorry -- not sure

**Comment by vreuter** [comment]
No worries, I've just added a couple cases to test that. The docs are updated a bit now, too.

**Pull request merged**
